// src/react/atropos-react.js
import React, { useEffect, useRef } from 'react';
// eslint-disable-next-line
import AtroposCore from '../esm/atropos.esm.js';

const paramsKeys = [
  'eventsEl',
  'alwaysActive',
  'activeOffset',
  'shadowOffset',
  'shadowScale',
  'duration',
  'rotate',
  'rotateTouch',
  'rotateXMax',
  'rotateYMax',
  'rotateXInvert',
  'rotateYInvert',
  'stretchX',
  'stretchY',
  'stretchZ',
  'commonOrigin',
  'shadow',
  'highlight',
  'onEnter',
  'onLeave',
  'onRotate',
];

const removeParamsKeys = (obj) => {
  const result = {};
  Object.keys(obj).forEach((key) => {
    if (!paramsKeys.includes(key)) result[key] = obj[key];
  });
  return result;
};

const extractParamsKeys = (obj) => {
  const result = {};
  Object.keys(obj).forEach((key) => {
    if (paramsKeys.includes(key)) result[key] = obj[key];
  });
  return result;
};

function Atropos(props) {
  const {
    component = 'div',
    children,
    rootChildren,
    scaleChildren,
    rotateChildren,
    className = '',
    scaleClassName = '',
    rotateClassName = '',
    innerClassName = '',

    ...rest
  } = props;

  const elRef = useRef(null);
  const atroposRef = useRef(null);

  const Component = component;

  const cls = (...args) => {
    return args.filter((c) => !!c).join(' ');
  };

  const init = () => {
    atroposRef.current = AtroposCore({
      el: elRef.current,
      ...extractParamsKeys(props),
    });
  };

  const destroy = () => {
    if (atroposRef.current) {
      atroposRef.current.destroy();
      atroposRef.current = null;
    }
  };

  useEffect(() => {
    if (elRef.current) {
      init();
    }

    return () => {
      destroy();
    };
  }, []);

  useEffect(() => {
    if (atroposRef.current) {
      atroposRef.current.params.onEnter = props.onEnter;
      atroposRef.current.params.onLeave = props.onLeave;
      atroposRef.current.params.onRotate = props.onRotate;
    }
    return () => {
      if (atroposRef.current) {
        atroposRef.current.params.onEnter = null;
        atroposRef.current.params.onLeave = null;
        atroposRef.current.params.onRotate = null;
      }
    };
  });

  return (
    <Component className={cls('atropos', className)} {...removeParamsKeys(rest)} ref={elRef}>
      <span className={cls('atropos-scale', scaleClassName)}>
        <span className={cls('atropos-rotate', rotateClassName)}>
          <span className={cls('atropos-inner', innerClassName)}>
            {children}
            {(props.highlight || typeof props.highlight === 'undefined') && (
              <span className="atropos-highlight" />
            )}
          </span>
          {rotateChildren}
          {(props.shadow || typeof props.shadow === 'undefined') && (
            <span className="atropos-shadow" />
          )}
        </span>
        {scaleChildren}
      </span>
      {rootChildren}
    </Component>
  );
}

export default Atropos;
export { Atropos };

// src/svelte/atropos-svelte.svelte
<script>
  import { onMount, onDestroy, createEventDispatcher } from 'svelte';
  // eslint-disable-next-line
  import AtroposCore from '../esm/atropos.esm.js';
  let className = '';
  export { className as class };
  export let scaleClass = '';
  export let rotateClass = '';
  export let innerClass = '';

  export let eventsEl = undefined;
  export let alwaysActive = undefined;
  export let activeOffset = undefined;
  export let shadowOffset = undefined;
  export let shadowScale = undefined;
  export let duration = undefined;
  export let rotate = undefined;
  export let rotateTouch = undefined;
  export let rotateXMax = undefined;
  export let rotateYMax = undefined;
  export let rotateXInvert = undefined;
  export let rotateYInvert = undefined;
  export let stretchX = undefined;
  export let stretchY = undefined;
  export let stretchZ = undefined;
  export let commonOrigin = true;
  export let shadow = true;
  export let highlight = true;

  const emit = createEventDispatcher();

  let elRef = null;
  let atroposRef = null;

  const cls = (...args) => {
    return args.filter((c) => !!c).join(' ');
  };

  const init = () => {
    atroposRef = AtroposCore({
      el: elRef,
      eventsEl,
      alwaysActive,
      activeOffset,
      shadowOffset,
      shadowScale,
      duration,
      rotate,
      rotateTouch,
      rotateXMax,
      rotateYMax,
      rotateXInvert,
      rotateYInvert,
      stretchX,
      stretchY,
      stretchZ,
      commonOrigin,
      onEnter() {
        emit('enter');
      },
      onLeave() {
        emit('leave');
      },
      onRotate(...args) {
        emit('rotate', args);
      },
    });
  };

  const destroy = () => {
    if (atroposRef) {
      atroposRef.destroy();
      atroposRef = null;
    }
  };

  onMount(() => {
    init();
  });
  onDestroy(() => {
    destroy();
  });
</script>

<div class={cls('atropos', className)} {...$$restProps} bind:this={elRef}>
  <span class={cls('atropos-scale', scaleClass)}>
    <span class={cls('atropos-rotate', rotateClass)}>
      <span class={cls('atropos-inner', innerClass)}>
        <slot />
        {#if highlight || typeof highlight === 'undefined'}
          <span class="atropos-highlight" />
        {/if}
      </span>
      <slot name="rotate" />
      {#if shadow || typeof shadow === 'undefined'}
        <span class="atropos-shadow" />
      {/if}
    </span>
    <slot name="scale" />
  </span>
  <slot name="root" />
</div>
