// playground/react/App.jsx
import React from 'react';
import Atropos from '../../build/react';

const App = () => {
  return (
    <div className="container">
      <Atropos className="atropos-banner" highlight={false} onEnter={() => console.log('enter')}>
        <img className="atropos-banner-spacer" src="./i/atropos-bg.svg" alt="" />
        <img data-atropos-offset="-4.5" src="./i/atropos-bg.svg" alt="" />
        <img data-atropos-offset="-2.5" src="./i/atropos-mountains.svg" alt="" />
        <img data-atropos-offset="0" src="./i/atropos-forest-back.svg" alt="" />
        <img data-atropos-offset="2" src="./i/atropos-forest-mid.svg" alt="" />
        <img data-atropos-offset="4" src="./i/atropos-forest-front.svg" alt="" />
        <img data-atropos-offset="5" src="./i/atropos-logo-en.svg" alt="" />
      </Atropos>
    </div>
  );
};

export default App;

// playground/svelte/App.svelte
<div class="container">
  <Atropos class="atropos-banner" highlight={false} on:enter={() => console.log('enter')}>
    <img class="atropos-banner-spacer" src="./i/atropos-bg.svg" alt="" />
    <img data-atropos-offset="-4.5" src="./i/atropos-bg.svg" alt="" />
    <img data-atropos-offset="-2.5" src="./i/atropos-mountains.svg" alt="" />
    <img data-atropos-offset="0" src="./i/atropos-forest-back.svg" alt="" />
    <img data-atropos-offset="2" src="./i/atropos-forest-mid.svg" alt="" />
    <img data-atropos-offset="4" src="./i/atropos-forest-front.svg" alt="" />
    <img data-atropos-offset="5" src="./i/atropos-logo-en.svg" alt="" />
  </Atropos>
</div>

<script>
import Atropos from '../../build/svelte';
</script>
