// playground/react/App.jsx
import React, { useState } from 'react';
import Atropos from '../../build/react';

const App = () => {
  const [rotate, setRotate] = useState(true);
  return (
    <>
      <div className="container">
        <Atropos className="atropos-banner" highlight={false} onEnter={() => console.log('enter')}>
          <img className="atropos-banner-spacer" src="./i/atropos-bg.svg" alt="" />
          <img data-atropos-offset="-4.5" src="./i/atropos-bg.svg" alt="" />
          <img data-atropos-offset="-2.5" src="./i/atropos-mountains.svg" alt="" />
          <img data-atropos-offset="0" src="./i/atropos-forest-back.svg" alt="" />
          <img data-atropos-offset="2" src="./i/atropos-forest-mid.svg" alt="" />
          <img data-atropos-offset="4" src="./i/atropos-forest-front.svg" alt="" />
          <img data-atropos-offset="5" src="./i/atropos-logo-en.svg" alt="" />
        </Atropos>
      </div>
      <button onClick={(e) => setRotate((v) => !v)}>Rotate turn {rotate ? 'off' : 'on'}</button>
    </>
  );
};

export default App;

// playground/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { AtroposOptions } from 'atropos/atropos';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  rotate: boolean = false;
  onEnter(event: Parameters<AtroposOptions['onEnter']>) {
    console.log(event);
  }
}

<div class="container">
  <atropos
    class="atropos-banner"
    [highlight]="false"
    [rotate]="rotate"
    [rotateXMax]="30"
    (onEnter)="onEnter($event)"
  >
    <img class="atropos-banner-spacer" src="assets/atropos-bg.svg" alt="" />
    <img data-atropos-offset="-4.5" src="assets/atropos-bg.svg" alt="" />
    <img data-atropos-offset="-2.5" src="assets/atropos-mountains.svg" alt="" />
    <img data-atropos-offset="0" src="assets/atropos-forest-back.svg" alt="" />
    <img data-atropos-offset="2" src="assets/atropos-forest-mid.svg" alt="" />
    <img data-atropos-offset="4" src="assets/atropos-forest-front.svg" alt="" />
    <img data-atropos-offset="5" src="assets/atropos-logo-en.svg" alt="" />
  </atropos>
</div>

<button (click)="rotate = !rotate">Rotate turn {{ rotate ? 'off' : 'on' }}</button>
