// src/angular/src/lib/atropos.component.ts
import { Component, ElementRef, Input, OnInit, Output, EventEmitter } from '@angular/core';
import AtroposCore, { AtroposInstance } from 'atropos';

@Component({
  selector: 'atropos',
  template: ` <div [ngClass]="'atropos ' + class">
    <span [ngClass]="'atropos-scale ' + scaleClassName">
      <span [ngClass]="'atropos-rotate ' + rotateClassName">
        <span [ngClass]="'atropos-inner ' + innerClassName">
          <ng-content></ng-content>
          <span *ngIf="highlight" class="atropos-highlight"></span>
        </span>
        <span *ngIf="shadow" class="atropos-shadow"></span>
      </span>
    </span>
  </div>`,
  styles: [],
})
export class AtroposComponent implements OnInit {
  @Input() shadow: boolean | undefined;
  @Input() highlight: boolean | undefined;
  @Input() class: string = '';
  @Input() eventsEl: any;
  @Input() alwaysActive: any;
  @Input() activeOffset: any;
  @Input() shadowOffset: any;
  @Input() shadowScale: any;
  @Input() duration: any;
  @Input() rotate: any;
  @Input() rotateTouch: any;
  @Input() rotateXMax: any;
  @Input() rotateYMax: any;
  @Input() rotateXInvert: any;
  @Input() rotateYInvert: any;
  @Input() stretchX: any;
  @Input() stretchY: any;
  @Input() stretchZ: any;
  @Input() commonOrigin: any;
  @Input() scaleClassName: string = '';
  @Input() rotateClassName: string = '';
  @Input() innerClassName: string = '';
  @Output() onEnter = new EventEmitter();
  @Output() onLeave = new EventEmitter();
  @Output() onRotate = new EventEmitter();
  ref: AtroposInstance | undefined;
  constructor(private elementRef: ElementRef) {}

  ngOnInit(): void {}

  ngAfterViewInit() {
    this.initAtropos();
  }

  initAtropos() {
    this.ref = AtroposCore({ el: this.elementRef.nativeElement });
  }
}

// src/react/atropos-react.js
import React, { useEffect, useRef } from 'react';
// eslint-disable-next-line
import AtroposCore from '../esm/atropos.esm.js';

const paramsKeys = [
  'eventsEl',
  'alwaysActive',
  'activeOffset',
  'shadowOffset',
  'shadowScale',
  'duration',
  'rotate',
  'rotateTouch',
  'rotateXMax',
  'rotateYMax',
  'rotateXInvert',
  'rotateYInvert',
  'stretchX',
  'stretchY',
  'stretchZ',
  'commonOrigin',
  'shadow',
  'highlight',
  'onEnter',
  'onLeave',
  'onRotate',
];

const removeParamsKeys = (obj) => {
  const result = {};
  Object.keys(obj).forEach((key) => {
    if (!paramsKeys.includes(key)) result[key] = obj[key];
  });
  return result;
};

const extractParamsKeys = (obj) => {
  const result = {};
  Object.keys(obj).forEach((key) => {
    if (paramsKeys.includes(key)) result[key] = obj[key];
  });
  return result;
};

function Atropos(props) {
  const {
    component = 'div',
    children,
    rootChildren,
    scaleChildren,
    rotateChildren,
    className = '',
    scaleClassName = '',
    rotateClassName = '',
    innerClassName = '',

    ...rest
  } = props;

  const elRef = useRef(null);
  const atroposRef = useRef(null);

  const Component = component;

  const cls = (...args) => {
    return args.filter((c) => !!c).join(' ');
  };

  const init = () => {
    atroposRef.current = AtroposCore({
      el: elRef.current,
      ...extractParamsKeys(props),
    });
  };

  const destroy = () => {
    if (atroposRef.current) {
      atroposRef.current.destroy();
      atroposRef.current = null;
    }
  };

  useEffect(() => {
    if (elRef.current) {
      init();
    }

    return () => {
      destroy();
    };
  }, []);

  useEffect(() => {
    if (atroposRef.current) {
      atroposRef.current.params.onEnter = props.onEnter;
      atroposRef.current.params.onLeave = props.onLeave;
      atroposRef.current.params.onRotate = props.onRotate;
    }
    return () => {
      if (atroposRef.current) {
        atroposRef.current.params.onEnter = null;
        atroposRef.current.params.onLeave = null;
        atroposRef.current.params.onRotate = null;
      }
    };
  });

  return (
    <Component className={cls('atropos', className)} {...removeParamsKeys(rest)} ref={elRef}>
      <span className={cls('atropos-scale', scaleClassName)}>
        <span className={cls('atropos-rotate', rotateClassName)}>
          <span className={cls('atropos-inner', innerClassName)}>
            {children}
            {(props.highlight || typeof props.highlight === 'undefined') && (
              <span className="atropos-highlight" />
            )}
          </span>
          {rotateChildren}
          {(props.shadow || typeof props.shadow === 'undefined') && (
            <span className="atropos-shadow" />
          )}
        </span>
        {scaleChildren}
      </span>
      {rootChildren}
    </Component>
  );
}

export default Atropos;
export { Atropos };
